#A compose file for quick testing
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
      - ./init_minio.sh:/init_minio.sh
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - fio-network

  fio:
    image: hossamelghamry/fio-nexus
    container_name: fio
    environment:
      - FIO_HOST=minio
      - FIO_PORT=9000 
      - IDENTITY=minioadmin
      - CREDENTIALS=minioadmin
      - BUCKET_NAME=test-bucket
    depends_on:
      - minio
    networks:
      - fio-network

networks:
  fio-network:

volumes:
  minio-data: