server.port=8080

#S3Proxy Configuration
s3proxy.identity=${S3PROXY_IDENTITY:identity}
s3proxy.credential=${S3PROXY_CREDENTIAL:credential}
s3proxy.endpoint=${S3PROXY_ENDPOINT:http://0.0.0.0:8181}

#JClouds Configuration
jclouds.provider=${JCLOUDS_PROVIDER:filesystem}
jclouds.identity=${JCLOUDS_IDENTITY:identity}
jclouds.credential=${JCLOUDS_CREDENTIAL:filesystem}
jclouds.filesystem-basedir=${JCLOUDS_FILESYSTEM_BASEDIR:/tmp/blobstore}
jclouds.endpoint=${JCLOUDS_ENDPOINT:http://localhost}

#Redis Configuration
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}

spring.batch.job.enabled=false
