{
 "title": "Nexus Benchmark",
 "time": { "from": "2025-03-11T10:49:40.991Z", "to": "2025-03-11T11:59:09.412Z" },
 "panels": [
  { "title": "Flamegraph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "flamegraph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "labelSelector": "{service_name=\"nexus\"}",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  { "title": "PUT Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Interception Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nexus_streamlet_function_put_execution_latency_seconds_sum[5m]) / rate(nexus_streamlet_function_put_execution_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_interceptor_PUT_request_interception_duration_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Storage Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_PUT_request_storage_operations_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forwarding Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_PUT_request_forward_operations_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Execution Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "nexus_streamlet_function_put_pipeline_execution_throughput{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forward Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_PUT_request_forward_throughput{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nexus_streamlet_function_put_execution_latency_seconds_sum[5m]) / rate(nexus_streamlet_function_put_execution_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_function_put_pipeline_execution_latency_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_PUT_request_storage_throughput{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forward Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_PUT_request_forward_size{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streamlet Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nexus_streamlet_function_put_execution_latency_seconds_sum[5m]) / rate(nexus_streamlet_function_put_execution_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_function_put_execution_latency_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_PUT_request_storage_size{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GET Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Interception Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nexus_streamlet_function_get_execution_latency_seconds_sum[5m]) / rate(nexus_streamlet_function_get_execution_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_interceptor_GET_request_interception_duration_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Storage Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_GET_request_storage_operations_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forwarding Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_GET_request_forward_operations_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Execution Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "nexus_streamlet_function_get_pipeline_execution_throughput{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forward Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_GET_request_forward_throughput{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nexus_streamlet_function_get_pipeline_execution_latency_seconds_sum[5m]) / rate(nexus_streamlet_function_get_pipeline_execution_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_function_get_pipeline_execution_latency_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Storage Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_GET_request_storage_throughput{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forward Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_GET_request_forward_size{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streamlet Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nexus_streamlet_function_get_execution_latency_seconds_sum[5m]) / rate(nexus_streamlet_function_get_execution_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_function_get_execution_latency_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_GET_request_storage_size{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multipart Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Initialization Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nexus_streamlet_interceptor_initiate_multipart_request_interception_duration_seconds_sum[5m]) / rate(nexus_streamlet_interceptor_initiate_multipart_request_interception_duration_seconds_count[5m])",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "histogram_quantile(0.95, rate(nexus_streamlet_interceptor_initiate_multipart_request_interception_duration_seconds_bucket[5m]))",
       "legendFormat": "95th Percentile"
      }
     ]
    },
    {
     "title": "Part Operations",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 9, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nexus_streamlet_interceptor_MULTIPART_upload_request_part_operations_total{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Complete Operations",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nexus_streamlet_interceptor_MULTIPART_upload_complete_operations_total{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upload Request Part Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "nexus_streamlet_interceptor_MULTIPART_upload_request_part_throughput{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Complete Upload Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "expr": "nexus_streamlet_interceptor_MULTIPART_upload_complete_throughput{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Abort Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(nexus_streamlet_interceptor_abort_multipart_request_interception_duration_seconds_sum[5m]) / rate(nexus_streamlet_interceptor_abort_multipart_request_interception_duration_seconds_count[5m])",
       "legendFormat": "Average Latency"
      },
      {
       "expr": "histogram_quantile(0.95, rate(nexus_streamlet_interceptor_abort_multipart_request_interception_duration_seconds_bucket[5m]))",
       "legendFormat": "95th Percentile"
      }
     ]
    },
    {
     "title": "Part Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "nexus_streamlet_interceptor_MULTIPART_upload_request_part_size{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Complete Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "nexus_streamlet_interceptor_MULTIPART_upload_complete_size{}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Metadata Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Update Object Metadata Tags Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nexus_streamlet_interceptor_UPDATE_metadata_tags_latency_seconds_sum[5m]) / rate(nexus_streamlet_interceptor_UPDATE_metadata_tags_latency_seconds_count[5m])",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_interceptor_UPDATE_metadata_tags_latency_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Update Metadata Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nexus_streamlet_interceptor_PUT_request_storage_operations_total{}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Misc.", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Streamlet Instantiation Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(nexus_streamlet_function_instantiation_duration_seconds_bucket[5m]))",
     "legendFormat": "95th Percentile"
    }
   ]
  }
 ]
}