#S3Proxy Configuration
s3proxy.identity=minioadmin
s3proxy.credential=minioadmin
s3proxy.endpoint=http://0.0.0.0:8182

#JClouds Configuration
jclouds.provider=s3
jclouds.identity=minioadmin
jclouds.credential=minioadmin
jclouds.filesystembasedir=/tmp/blobstore
jclouds.endpoint=http://localhost:9000
jclouds.s3.virtual-host-bucket=false

#Redis Configuration
redis.host=localhost
redis.port=6379

#Micrometer Configuration
management.defaults.metrics.export.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true

#HTTP Server
webserver.port=8080

#Nexus Configuration
# Important: the combination of region and hardware should be unique,
# as it is what the Nexus worker instance uses to select
nexus.region=CLOUD
nexus.hardware=NONE
