#S3Proxy Configuration
s3proxy.identity=minioadmin
s3proxy.credential=minioadmin
s3proxy.endpoint=http://0.0.0.0:8181

#JClouds Configuration
jclouds.provider=filesystem
jclouds.identity=minioadmin
jclouds.credential=minioadmin
jclouds.filesystembasedir=/tmp/blobstore
jclouds.endpoint=http://localhost:9000
jclouds.s3.virtual-host-bucket=false

#Redis Configuration
redis.host=localhost
redis.port=6379

#Micrometer Configuration
management.defaults.metrics.export.enabled=true
management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true

#HTTP Server
webserver.port=8080

#Nexus Configuration
# Important: the combination of region and hardware should be unique,
# as it is what the Nexus worker instance uses to select
nexus.region=EDGE
nexus.hardware=NONE
nexus.swarmlet=nexus-svc
nexus.clusterVirtualNodes=5
nexus.keepaliveInterval=10000
nexus.timeout=30000
nexus.stateBackendType=redis
nexus.redisStateBackendHost=localhost
nexus.redisStateBackendPort=6379
nexus.rocksDBStateBackendPath=/tmp/rocksdb/
