apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-svc
  namespace: nexus-ns
spec:
  ports:
    - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: nexus-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - image: raulgracia/kafka:3.7.0-tiered-storage
          imagePullPolicy: IfNotPresent
          name: kafka-broker
          ports:
            - containerPort: 9092
          env:
            #Kafka configuration
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT #Zookeeper host:port
              value: "zookeeper-svc:2181"
            - name: KAFKA_LISTENERS
              #PLAINTEXT:// Exposes Kafka on localhost:9092, Might be useful if there is a sidecar implementation
              #BROKER:// Exposes Broker to other brokers (not relevant here)
              value: PLAINTEXT://0.0.0.0:9092,BROKER://0.0.0.0:29092
              #IMPORTANT: Expose Kafka to outside pods
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-svc:9092,BROKER://kafka-broker:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP #Maps each listener to security protocol PLAINTEXT
              value: PLAINTEXT:PLAINTEXT,BROKER:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME #Unique name for broker
              value: BROKER

              #Log management
              #Configures the number and properties of replicas for the cluster
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"

              # Tiered Storage Configuration
              # Increase Tiered Storage log level
            - name: KAFKA_LOG4J_LOGGERS
              value: io.aiven.kafka.tieredstorage=DEBUG
              # Frequency to check if logs should be retained inside the broker's local disk
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: "10000"
              # Enable Tiered Storage
            - name: KAFKA_REMOTE_LOG_STORAGE_SYSTEM_ENABLE
              value: "true"
              #IMPORTANT: How much time to execute tiered storage offloading
            - name: KAFKA_REMOTE_LOG_MANAGER_TASK_INTERVAL_MS
              value: "5000"

              # Remote metadata manager
            - name: KAFKA_REMOTE_LOG_METADATA_MANAGER_CLASS_NAME
              value: org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager
            - name: KAFKA_REMOTE_LOG_METADATA_MANAGER_LISTENER_NAME
              value: BROKER
            - name: KAFKA_RLMM_CONFIG_REMOTE_LOG_METADATA_TOPIC_REPLICATION_FACTOR
              value: "1"

            # Remote storage manager
            # Variables to define types and sizes for log storage management (Currently not in use)
            - name: KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_PATH
              value: /tiered-storage-for-apache-kafka/core/*:/tiered-storage-for-apache-kafka/s3/*
            - name: KAFKA_REMOTE_LOG_STORAGE_MANAGER_CLASS_NAME
              value: io.aiven.kafka.tieredstorage.RemoteStorageManager
            - name: KAFKA_RSM_CONFIG_CHUNK_SIZE
              value: "4194304"
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_CLASS
              value: io.aiven.kafka.tieredstorage.fetch.cache.DiskChunkCache
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_PATH
              value: /home/appuser/kafka-tiered-storage-cache
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_SIZE
              value: "1073741824"
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_PREFETCH_MAX_SIZE
              value: "16777216"
            - name: KAFKA_RSM_CONFIG_FETCH_CHUNK_CACHE_RETENTION_MS
              value: "600000"
            - name: KAFKA_RSM_CONFIG_CUSTOM_METADATA_FIELDS_INCLUDE
              value: REMOTE_SIZE

              # Storage backend
            # - name: KAFKA_RSM_CONFIG_KEY_PREFIX #Stored keys prefix
            #   value: scope/stream/
            - name: KAFKA_RSM_CONFIG_STORAGE_BACKEND_CLASS #S3-minio Storage class
              value: io.aiven.kafka.tieredstorage.storage.s3.S3Storage
              #IMPORTANT: Backend storage endpoint. Nexus svc is set here
            - name: KAFKA_RSM_CONFIG_STORAGE_S3_ENDPOINT_URL
              value: "http://nexus-svc:9092"
            - name: KAFKA_RSM_CONFIG_STORAGE_S3_BUCKET_NAME #Bucket name to store data in
              value: kafka-bucket
            - name: KAFKA_RSM_CONFIG_STORAGE_S3_REGION
              value: us-east-1
            - name: KAFKA_RSM_CONFIG_STORAGE_S3_PATH_STYLE_ACCESS_ENABLED
              value: "true"

              #Currently using no authorization in Nexus
              #But from Nexus's POV, these are JCloud's identity and credential fields
              #From Minio's POV, these are MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
            - name: KAFKA_RSM_CONFIG_STORAGE_AWS_ACCESS_KEY_ID
              value: dev-identity
            - name: KAFKA_RSM_CONFIG_STORAGE_AWS_SECRET_ACCESS_KEY
              value: dev-credential
            # ADDED
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "10485760"
            - name: KAFKA_METADATA_LOG_SEGMENT_BYTES
              value: "10485760"
            - name: S3PROXY_ENDPOINT
              value: "http://nexus-svc:9092"
