apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: nexus-test
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-ss
  namespace: nexus-test
spec:
  serviceName: minio-svc
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: "dev-identity"
            - name: MINIO_ROOT_PASSWORD
              value: "dev-credential"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 128Mi
