package io.nexus.streamlets.compiler;

import io.nexus.streamlets.metadata.MetadataService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.tools.*;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.net.URI;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * A utility class for dynamically compiling and loading Java classes at runtime.
 * This class allows compiling Java source code in-memory and loading the resulting bytecode.
 *
 * The compilation process stores the generated bytecode in a map, which can then be used
 * to dynamically load and instantiate classes.
 */
 public class DynamicCompiler {
    private static final Logger logger = LoggerFactory.getLogger(DynamicCompiler.class);
    private final JavaCompiler compiler;
    private final StandardJavaFileManager standardFileManager;
    private final Map<String, byte[]> compiledClasses = new HashMap<>();

    public DynamicCompiler() {
        compiler = ToolProvider.getSystemJavaCompiler();
        standardFileManager = compiler.getStandardFileManager(null, null, null);
    }

    public boolean compile(String className, String sourceCode) {
        InMemoryJavaFileObject file = new InMemoryJavaFileObject(className, sourceCode);
        DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
        InMemoryFileManager fileManager = new InMemoryFileManager(standardFileManager);

        JavaCompiler.CompilationTask task = compiler.getTask(
                null, fileManager, diagnostics, null, null, Collections.singletonList(file)
        );

        boolean success = task.call();
        if (success) {
            compiledClasses.putAll(fileManager.getCompiledClasses());
        } else {
            diagnostics.getDiagnostics().forEach(d ->
                    logger.error("Compilation error: " + d.getMessage(null)));
        }
        return success;
    }

    public Class<?> loadClass(String className) throws Exception {
        return new InMemoryClassLoader(compiledClasses).loadClass(className);
    }

    // --- InMemoryFileManager ---
    private static class InMemoryFileManager extends ForwardingJavaFileManager<StandardJavaFileManager> {
        private final Map<String, InMemoryByteCode> compiledByteCodes = new HashMap<>();

        protected InMemoryFileManager(StandardJavaFileManager fileManager) {
            super(fileManager);
        }

        @Override
        public JavaFileObject getJavaFileForOutput(Location location, String className, JavaFileObject.Kind kind, FileObject sibling) {
            InMemoryByteCode byteCode = new InMemoryByteCode(className);
            compiledByteCodes.put(className, byteCode);
            return byteCode;
        }

        public Map<String, byte[]> getCompiledClasses() {
            Map<String, byte[]> bytecodeMap = new HashMap<>();
            compiledByteCodes.forEach((name, byteCode) -> bytecodeMap.put(name, byteCode.getBytes()));
            return bytecodeMap;
        }
    }

    // --- InMemoryByteCode ---
    private static class InMemoryByteCode extends SimpleJavaFileObject {
        private final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        protected InMemoryByteCode(String className) {
            super(URI.create("bytes:///" + className), Kind.CLASS);
        }

        @Override
        public OutputStream openOutputStream() {
            return outputStream;
        }

        public byte[] getBytes() {
            return outputStream.toByteArray();
        }
    }
}
