apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchmark
  name: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      containers:
        - image: raulgracia/openmessaging-benchmark:data-supplier-2
          imagePullPolicy: Always
          name: benchmark
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
